import type { Artist, Event, Task, Venue } from "./types";

export const sampleVenues: Venue[] = [
  {
    id: "venue-kupfersaal",
    name: "Kupfersaal Leipzig",
    city: "Leipzig",
    capacity: 420,
    color: "#14b8a6",
    type: "Theater",
    monthlySlots: 22,
    bookedSlots: 18,
    searchTerms: ["jazz", "hof", "theater", "innenstadt"],
  },
  {
    id: "venue-lindenhof",
    name: "Lindenhof Buehne",
    city: "Augsburg",
    capacity: 180,
    color: "#8b5cf6",
    type: "Club",
    monthlySlots: 18,
    bookedSlots: 12,
    searchTerms: ["kabarett", "club", "kleinkunst"],
  },
  {
    id: "venue-kulturdeck",
    name: "Kulturdeck Koeln",
    city: "Koeln",
    capacity: 260,
    color: "#f59e0b",
    type: "Open Air",
    monthlySlots: 16,
    bookedSlots: 9,
    searchTerms: ["poetry", "sommer", "open air"],
  },
  {
    id: "venue-schwarzer-saal",
    name: "Schwarzer Saal",
    city: "Leipzig",
    capacity: 140,
    color: "#f43f5e",
    type: "Theater",
    monthlySlots: 14,
    bookedSlots: 8,
    searchTerms: ["chanson", "lesung", "theater"],
  },
];

export const sampleArtists: Artist[] = [
  {
    id: "artist-mara-sol",
    stageName: "Mara Sol",
    contactName: "Mara Sommer",
    genres: ["Jazz", "Soul"],
    rating: 5,
    isFavorite: true,
  },
  {
    id: "artist-ernst-klein",
    stageName: "Ernst Klein",
    contactName: "Ernst Klein",
    genres: ["Kabarett", "Satire"],
    rating: 4,
    isFavorite: true,
  },
  {
    id: "artist-wortwechsel",
    stageName: "Wortwechsel Kollektiv",
    contactName: "Lea Brandt",
    genres: ["Poetry Slam", "Lesung"],
    rating: 4,
    isFavorite: false,
  },
  {
    id: "artist-trio-luna",
    stageName: "Trio Luna",
    contactName: "Jonas Weber",
    genres: ["Chanson", "Theatermusik"],
    rating: 5,
    isFavorite: false,
  },
];

export const sampleEvents: Event[] = [
  {
    id: "event-jazz-im-hof",
    title: "Jazz im Hof",
    subtitle: "Sommerabend mit Mara Sol",
    date: "2026-07-09",
    startTime: "20:00",
    endTime: "21:45",
    venueId: "venue-kupfersaal",
    artistIds: ["artist-mara-sol"],
    status: "published",
    ticketPrice: 28,
    capacity: 320,
    soldTickets: 286,
    revenueActual: 13800,
    revenueTarget: 15000,
    gemaStatus: "pending",
    gemaDueDate: "2026-07-09",
    slug: "2026-07-09-jazz-im-hof",
  },
  {
    id: "event-kabarett-stadtgefluester",
    title: "Kabarett: Stadtgefluester",
    subtitle: "Politischer Abend mit Ernst Klein",
    date: "2026-07-11",
    startTime: "19:30",
    endTime: "21:10",
    venueId: "venue-lindenhof",
    artistIds: ["artist-ernst-klein"],
    status: "published",
    ticketPrice: 24,
    capacity: 180,
    soldTickets: 142,
    revenueActual: 9400,
    revenueTarget: 10800,
    gemaStatus: "pending",
    gemaDueDate: "2026-07-11",
    slug: "2026-07-11-kabarett-stadtgefluester",
  },
  {
    id: "event-poetry-slam",
    title: "Poetry Slam Spezial",
    subtitle: "Stadtfinale der Wortbuehne",
    date: "2026-07-13",
    startTime: "20:00",
    endTime: "22:15",
    venueId: "venue-kulturdeck",
    artistIds: ["artist-wortwechsel"],
    status: "planned",
    ticketPrice: 18,
    capacity: 250,
    soldTickets: 160,
    revenueActual: 7200,
    revenueTarget: 9000,
    gemaStatus: "pending",
    gemaDueDate: "2026-07-14",
    slug: "2026-07-13-poetry-slam-spezial",
  },
  {
    id: "event-sommerbuehne-impro",
    title: "Sommerbuehne Impro",
    subtitle: "Improtheater unter freiem Himmel",
    date: "2026-07-17",
    startTime: "19:00",
    endTime: "20:40",
    venueId: "venue-kulturdeck",
    artistIds: ["artist-wortwechsel"],
    status: "planned",
    ticketPrice: 20,
    capacity: 260,
    soldTickets: 130,
    revenueActual: 6500,
    revenueTarget: 10400,
    gemaStatus: "not_required",
    gemaDueDate: null,
    slug: "2026-07-17-sommerbuehne-impro",
  },
  {
    id: "event-chanson-nacht",
    title: "Chanson Nacht",
    subtitle: "Trio Luna spielt Brel und Brecht",
    date: "2026-07-21",
    startTime: "20:00",
    endTime: "22:00",
    venueId: "venue-schwarzer-saal",
    artistIds: ["artist-trio-luna"],
    status: "planned",
    ticketPrice: 26,
    capacity: 140,
    soldTickets: 96,
    revenueActual: 6250,
    revenueTarget: 7800,
    gemaStatus: "submitted",
    gemaDueDate: "2026-07-23",
    slug: "2026-07-21-chanson-nacht",
  },
  {
    id: "event-nacht-der-lieder",
    title: "Nacht der Lieder",
    subtitle: "Doppelkonzert im Kupfersaal",
    date: "2026-07-29",
    startTime: "20:00",
    endTime: "22:30",
    venueId: "venue-kupfersaal",
    artistIds: ["artist-mara-sol", "artist-trio-luna"],
    status: "draft",
    ticketPrice: 32,
    capacity: 400,
    soldTickets: 98,
    revenueActual: 3100,
    revenueTarget: 17000,
    gemaStatus: "not_required",
    gemaDueDate: null,
    slug: "2026-07-29-nacht-der-lieder",
  },
];

export const sampleTasks: Task[] = [
  {
    id: "task-1",
    title: "GEMA-Musikfolge fuer Jazz im Hof anfordern",
    dueDate: "2026-07-08",
    eventId: "event-jazz-im-hof",
    category: "gema",
    completed: false,
    assignee: "Clara",
  },
  {
    id: "task-2",
    title: "Technik-Rider Lindenhof bestaetigen",
    dueDate: "2026-07-09",
    eventId: "event-kabarett-stadtgefluester",
    category: "tech",
    completed: false,
    assignee: "Torsten",
  },
  {
    id: "task-3",
    title: "Newsletter Segment Leipzig versenden",
    dueDate: "2026-07-10",
    eventId: "event-jazz-im-hof",
    category: "marketing",
    completed: false,
    assignee: "Mira",
  },
  {
    id: "task-4",
    title: "Kuenstlervertrag Trio Luna gegenzeichnen",
    dueDate: "2026-07-12",
    eventId: "event-chanson-nacht",
    category: "booking",
    completed: false,
    assignee: "Clara",
  },
  {
    id: "task-5",
    title: "Abendkasse Poetry Slam vorbereiten",
    dueDate: "2026-07-13",
    eventId: "event-poetry-slam",
    category: "finance",
    completed: false,
    assignee: "Andreas",
  },
  {
    id: "task-6",
    title: "Pressefoto fuer Sommerbuehne freigeben",
    dueDate: "2026-07-14",
    eventId: "event-sommerbuehne-impro",
    category: "marketing",
    completed: false,
    assignee: "Mira",
  },
  {
    id: "task-7",
    title: "GEMA Rueckfrage Poetry Slam klaeren",
    dueDate: "2026-07-14",
    eventId: "event-poetry-slam",
    category: "gema",
    completed: false,
    assignee: "Torsten",
  },
  {
    id: "task-8",
    title: "Kulturdeck Bestuhlung final melden",
    dueDate: "2026-07-15",
    eventId: "event-sommerbuehne-impro",
    category: "general",
    completed: false,
    assignee: "Andreas",
  },
  {
    id: "task-9",
    title: "Posterdatei archivieren",
    dueDate: "2026-07-07",
    eventId: "event-jazz-im-hof",
    category: "marketing",
    completed: true,
    assignee: "Mira",
  },
];
